# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifeq ($(MAIN),1)
unexport MAIN

# Main section

URVERSION = $(shell urweb -version)
.PHONY: all
all: ./HomePage.db ./HomePage.exe ./HomePage.sql ./Makefile
./HomePage.db: ./HomePage.exe ./HomePage.sql ./Makefile
	dropdb --if-exists HomePage
	createdb HomePage
	psql -f ./HomePage.sql HomePage
	touch ./HomePage.db
./HomePage.exe: .fix-multy1
./HomePage.urp: ./HomePage.ur ./HomePage.urs ./Makefile ./lib/urweb-monad-pack/test/XmlGen.urp .cake3/tmpHomePage.in0
	cat .cake3/tmpHomePage.in0 > ./HomePage.urp
.cake3/tmpHomePage.in0: ./Makefile
	-rm -rf .cake3/tmpHomePage.in0
	echo 'debug' >> .cake3/tmpHomePage.in0
	echo 'sql ./HomePage.sql' >> .cake3/tmpHomePage.in0
	echo 'library ./lib/urweb-monad-pack/test/XmlGen' >> .cake3/tmpHomePage.in0
	echo '' >> .cake3/tmpHomePage.in0
	echo './HomePage' >> .cake3/tmpHomePage.in0
./HomePage.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: ./HomePage.urp ./Makefile $(call GUARD,URVERSION)
	urweb -dbms postgres ./HomePage
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

ifneq ($(MAKECMDGOALS),clean)

.PHONY: all
all: .fix-multy1
.PHONY: ./HomePage.db
./HomePage.db: .fix-multy1
.PHONY: ./HomePage.exe
./HomePage.exe: .fix-multy1
.PHONY: ./HomePage.urp
./HomePage.urp: .fix-multy1
.PHONY: .cake3/tmpHomePage.in0
.cake3/tmpHomePage.in0: .fix-multy1
.PHONY: ./HomePage.sql
./HomePage.sql: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	$(MAKE) -C ./lib/urweb-monad-pack -f Makefile test/XmlGen.urp
	MAIN=1 $(MAKE) -f ./Makefile $(MAKECMDGOALS)

endif
.PHONY: clean
clean: 
	-rm ./HomePage.db ./HomePage.exe ./HomePage.sql ./HomePage.urp .cake3/tmpHomePage.in0
	-rm -rf .cake3

endif
